# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asMatrix <- function(rp, cp, z, nrows, ncols) {
    .Call('_SCP_asMatrix', PACKAGE = 'SCP', rp, cp, z, nrows, ncols)
}

