# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MergeRowsForDense <- function(matrix, groupings) {
    .Call('_SCP_MergeRowsForDense', PACKAGE = 'SCP', matrix, groupings)
}

MergeRowsForSparse <- function(matrix, groupings) {
    .Call('_SCP_MergeRowsForSparse', PACKAGE = 'SCP', matrix, groupings)
}

MergeRowsC <- function(matrix, groupings) {
    .Call('_SCP_MergeRowsC', PACKAGE = 'SCP', matrix, groupings)
}

asMatrixC <- function(rp, cp, z, nrows, ncols) {
    .Call('_SCP_asMatrixC', PACKAGE = 'SCP', rp, cp, z, nrows, ncols)
}

